template = "https://github.com/giellalt/template-lang-und"
rev_id = 184
template_sha = "81054d8e9f74c26fbd8043f172b50a9f71cdd92a"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
