template = "https://github.com/giellalt/template-lang-und"
rev_id = 145
template_sha = "55ee7c3f07e07c398941f21d65d3a49bdef2884c"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
