template = "https://github.com/giellalt/template-lang-und"
rev_id = 103
template_sha = "9004feb674fd3fd06f5e92fdf7f94148f238dfad"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
