template = "https://github.com/giellalt/template-lang-und"
rev_id = 149
template_sha = "cc95a956f6b906ba7206f610796a2e6edcf8f478"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
