template = "https://github.com/giellalt/template-lang-und"
rev_id = 178
template_sha = "0e977ab51a115099656def83b47120d28edcd023"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
