template = "https://github.com/giellalt/template-lang-und"
rev_id = 143
template_sha = "8a517766840a1747e572aaf865c94bcccb729353"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
