template = "https://github.com/giellalt/template-lang-und"
rev_id = 167
template_sha = "4e541d9adc1d60ff89f947acabb41520c993c85f"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
