template = "https://github.com/giellalt/template-lang-und"
rev_id = 128
template_sha = "d3822979aa3293c4fa535cdebe16b2b39ffde39f"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
