template = "https://github.com/giellalt/template-lang-und"
rev_id = 75
template_sha = "3632636146f363f95b04c7b5ec97661cf508ab68"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
