template = "https://github.com/giellalt/template-lang-und"
rev_id = 154
template_sha = "42b3e17adab03a6d3de2a529e992f1c09cb4cf0f"

[replacements]
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
